server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: ms-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_order?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 99168844Jo#

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true


